/* ═══════════════════════════════════════════════════════════════
   sd_cast_index.js — THE PEOPLE (browseable cast index)
   Data-driven from supporting_cast_engine.js (28 supporting characters),
   baked here as a flat, offline, ES5-safe list so the Browse 'People'
   section + tap-to-know popovers work with NO AI server.
   Generated 2026-09-22. To refresh: re-run the extractor over
   supporting_cast_engine.js. Additive — safe to load anywhere.
   ═══════════════════════════════════════════════════════════════ */
var SD_CAST = {
  members: [
    {id:'kael', name:'Kael Voss', role:'Vocals', color:'#ef4444', icon:'🎤', soul:'Ka-El', ability:'Voice Manipulation'},
    {id:'mira', name:'Mira Chen', role:'Lead Guitar', color:'#f59e0b', icon:'🎸', soul:'Mir-Ahk', ability:'Frequency Sight'},
    {id:'oren', name:'Oren Malik', role:'Drums', color:'#10b981', icon:'🥁', soul:'Ori-Tahn', ability:'Temporal Drift'},
    {id:'jude', name:'Jude Okafor', role:'Rhythm Guitar', color:'#8b5cf6', icon:'🎸', soul:'Ju-Dael', ability:'Emotional Resonance'},
    {id:'zara', name:'Zara Kovač', role:'Bass', color:'#22d3ee', icon:'🎵', soul:'Zar-Ahn', ability:'Harmonic Bridge'}
  ],
  people: [
  {id:'troy_jackson', name:'Troy Jackson', circle:'kael', circleName:'Kael Voss', color:'#ef4444', relationship:'Best friend since 7th grade', knows:'Strongly suspects', knowsRaw:'suspects_strongly', bio:'Loud, loyal, physical energy. The kind of friend who talks enough for two people. Works at AutoZone, content with his life in a way Kael envies. Stocky, Black, always moving — hands gesturing, body shifting, can\'t sit still. Heart of gold under a mouth that never stops.'},
  {id:'nina_osei', name:'Nina Osei', circle:'kael', circleName:'Kael Voss', color:'#ef4444', relationship:'The Almost — romantic connection at 17 that never became official', knows:'Senses something', knowsRaw:'felt_something', bio:'Ghanaian-American. Direct, fearless, emotionally intelligent. Became a nurse practitioner — works at the same hospital as Oren (they don\'t know each other yet). Beautiful in a way that\'s confident, not performative. Says exactly what she means. Doesn\'t play games. The kind of woman who makes you feel like a coward for not being honest.'},
  {id:'raylan_meeks', name:'Raylan Meeks', circle:'kael', circleName:'Kael Voss', color:'#ef4444', relationship:'Warehouse coworker, shift buddy for 3 years', knows:'No idea', knowsRaw:'nothing', bio:'White, lanky, early 30s, divorced dad of one. Dry humor. Smokes on break. Has the slightly defeated air of someone who peaked in his 20s and is making peace with the plateau. Good heart, low ambition. Reads thriller novels on break. The kind of coworker who makes a bad job bearable.'},
  {id:'elena_voss', name:'Elena Voss', circle:'kael', circleName:'Kael Voss', color:'#ef4444', relationship:'Younger sister, 4 years gap', knows:'Studying it unaware', knowsRaw:'studying_it_unknowingly', bio:'Energetic, smart, socially fearless. The opposite of Kael in every external way — loud, social, goes to every party. But internally they\'re the same: both watching, both analyzing, both a little too aware of how people work. She drags him to shows. Gets him out of the apartment. Would fight God for him.'},
  {id:'dominic_reyes', name:'Dominic \'Dom\' Reyes', circle:'kael', circleName:'Kael Voss', color:'#ef4444', relationship:'Former best friend / bandmate (ages 15-18), now distant', knows:'Remembers fragments', knowsRaw:'remembers_something', bio:'Dominican. Ambitious, restless, always climbing. Left their small city for LA and never looked back. Charming, talented, slightly selfish in the way people who chase dreams have to be. Has the kind of life Kael was \'supposed\' to have — music career, momentum, forward motion. Feels guilty about drifting from Kael but not enough to come back.'},
  {id:'sage_kowalski', name:'Sage Kowalski', circle:'mira', circleName:'Mira Chen', color:'#f59e0b', relationship:'Best and only friend since age 14', knows:'Knows everything', knowsRaw:'full_knowledge', bio:'White, non-binary, tattoo artist. All black before it was aesthetic. Fierce loyalty masked by casual affect. Dry humor that borders on morbid. The friend who shows up at midnight without being asked. Steady in a way that seems impossible for someone covered in stick-and-poke tattoos and living off ramen. Uses they/them.'},
  {id:'cameron_lewis', name:'Cameron \'Cam\' Lewis', circle:'mira', circleName:'Mira Chen', color:'#f59e0b', relationship:'First real love, dated 5 months at age 16', knows:'Affected unknowingly', knowsRaw:'experienced_effects_unknowingly', bio:'Black, gentle, emotionally intelligent. The kind of boy who asks \'no but how are you ACTUALLY doing.\' Studies music therapy in grad school now. Still has that sweetness — hasn\'t been hardened by the world. Plays keyboard beautifully. Remembers Mira like a song he can\'t quite finish.'},
  {id:'iris_delgado', name:'Iris Delgado', circle:'mira', circleName:'Mira Chen', color:'#f59e0b', relationship:'Guitar student turned friend/protégé', knows:'Senses something', knowsRaw:'nothing_but_senses_something', bio:'Mexican-American, 17, lives with her grandmother. Bright, curious, hungry to learn. Not yet jaded. Reminds Mira of what she COULD have been if the entities hadn\'t claimed her so young. Plays guitar with raw emotion that makes up for developing technique. Talks fast, laughs loud, wears her heart completely visible.'},
  {id:'sandra_chen', name:'Sandra Chen née Williams', circle:'mira', circleName:'Mira Chen', color:'#f59e0b', relationship:'Mother', knows:'Believes but denies', knowsRaw:'believes_but_denies', bio:'Black American, former dancer (modern/contemporary — gave it up when she married David). Warm, fierce, conflicted. Her love for Mira is enormous and complicated by fear. She moves like a dancer still — graceful, physical, present. Sings while cooking (gospel, jazz, R&B). Her voice is remarkable. She never pursued it.'},
  {id:'jason_chen', name:'Jason Chen', circle:'mira', circleName:'Mira Chen', color:'#f59e0b', relationship:'Older brother, 3 years gap', knows:'Actively denies', knowsRaw:'actively_denies', bio:'Chinese-American. Finance career, good apartment, gym body, active social life. Everything Mira isn\'t, by design. He\'s not cruel — he\'s UNCOMFORTABLE. Her weirdness makes him question the normal life he\'s built, so he denies it. They barely talk. Not because of a fight — because they have nothing in common. The silence at family dinner is thick.'},
  {id:'darius_cole', name:'Darius Cole', circle:'jude', circleName:'Jude Okafor', color:'#8b5cf6', relationship:'Best friend since age 14, the brother from another', knows:'Knows something is different', knowsRaw:'knows_something_is_different', bio:'Black, 6\'2\\", firefighter now. Steady, warm, loyal to a fault. Plays guitar too (blues, funk — lighter stuff). Has the easy confidence of someone who likes his life and knows who he is. The anti-Jude in temperament — calm where Jude rages, light where Jude goes dark. Their friendship works because Darius is unshakeable.'},
  {id:'aisha_carter', name:'Aisha Carter', circle:'jude', circleName:'Jude Okafor', color:'#8b5cf6', relationship:'Ex-girlfriend, dated ages 16-18. First real love.', knows:'Lived the consequences', knowsRaw:'experienced_the_consequences', bio:'Black, tall (5\'10\\"), graceful. Physical therapist now. Married. Happy. Moved on in all the ways that matter. But she still thinks about Jude sometimes — not with love, but with worry. \'I hope he found someone who could handle it.\' She has the calm that Jude always needed and was too afraid to keep.'},
  {id:'big_mike_okonkwo', name:'Michael \'Big Mike\' Okonkwo', circle:'jude', circleName:'Jude Okafor', color:'#8b5cf6', relationship:'Demolition crew foreman, mentor figure', knows:'Suspicious but practical', knowsRaw:'suspicious_but_practical', bio:'Nigerian-American (Igbo). Built like a barrel. Laughs from his belly. Ran the demo crew for 12 years. Treats his guys like family — feeds them, covers for them, kicks their ass when needed. Has two daughters he shows phone photos of CONSTANTLY. Deeply religious (Catholic) in a quiet, personal way.'},
  {id:'faith_okafor', name:'Faith Okafor', circle:'jude', circleName:'Jude Okafor', color:'#8b5cf6', relationship:'Twin sister', knows:'Intuits deeply', knowsRaw:'intuits_deeply', bio:'Nigerian-American, petite (5\'3\\" to his 6\'2\\"), brilliant, intensely focused. Studies stars for a living. Speaks softly but with precision — every word chosen. Has their mother Grace\'s calm and their father Manny\'s intellect. The family\'s golden child without ever asking to be.'},
  {id:'kwame_ansah', name:'Kwame Ansah', circle:'jude', circleName:'Jude Okafor', color:'#8b5cf6', relationship:'Friend since age 16, the social connector', knows:'Nothing real', knowsRaw:'nothing_real', bio:'Ghanaian-American. Short, wiry, talks at double speed. Runs a sneaker resale business (making real money). Knows EVERYBODY. The guy who has a guy for everything. Pure hustle energy. Heart is good but attention span is short — everything is transactional on the surface, genuine underneath.'},
  {id:'olivia_grant', name:'Olivia Grant', circle:'zara', circleName:'Zara Kovač', color:'#22d3ee', relationship:'Best friend since age 15, the one constant', knows:'Nothing real but says the truth as joke', knowsRaw:'nothing_real_but_says_the_truth_as_joke', bio:'White, redhead, chaos goblin energy. Art school dropout, now a barista (and happy about it). Lives loud, loves hard, breaks things (emotionally, sometimes physically). The kind of friend who texts at 3 AM \'I just had a thought\' and the thought is always insane and always worth hearing. Zero judgment. Infinite curiosity.'},
  {id:'theo_park', name:'Theo Park', circle:'zara', circleName:'Zara Kovač', color:'#22d3ee', relationship:'Ex-boyfriend, dated ages 17-19. The longest relationship Zara\'s had.', knows:'Sensed the performance', knowsRaw:'sensed_the_performance', bio:'Korean-American. Session bassist now — plays in other people\'s bands. Good but not great. Quiet, deep thinker, emotionally persistent in a way that exhausted Zara. Wanted MORE. Deeper. Closer. Every time he pushed, she gave him another layer of performance instead of truth. He could tell. It broke him slowly.'},
  {id:'jesse_morrow', name:'Jesse Morrow', circle:'zara', circleName:'Zara Kovač', color:'#22d3ee', relationship:'Fellow sound tech, co-worker at The Frequency venue', knows:'Professionally baffled', knowsRaw:'professionally_baffled', bio:'White, scruffy, lives in band t-shirts and cargo shorts. Went to audio engineering school (unlike Zara, who just showed up knowing everything). Passionate about sound in a nerdy, technical way. Good at his job — but Zara is on another level and he knows it. No resentment though — genuine admiration. Slight crush he\'ll never act on.'},
  {id:'ante_kovac', name:'Ante Kovač', circle:'zara', circleName:'Zara Kovač', color:'#22d3ee', relationship:'Father', knows:'Has always known', knowsRaw:'knows_something_since_birth', bio:'Croatian immigrant, former military radio operator (Yugoslav Wars). Now an electrician. Practical, quiet, strong hands. Reads the Croatian newspaper online every morning. Calls his mother in Split every Sunday. Has the heavy stillness of someone who survived something enormous and chose silence over explanation. Not cold — just deep.'},
  {id:'jamie_deluca', name:'Jamie DeLuca', circle:'zara', circleName:'Zara Kovač', color:'#22d3ee', relationship:'The 3 AM friend — not a best friend, a witness', knows:'Heard truth, let it pass', knowsRaw:'heard_the_truth_and_let_it_pass', bio:'Italian-American. Insomniac by nature, night-shift by choice. Moves through the world at a slower speed than everyone else — deliberate, unhurried, completely at ease with silence. Wipes counters like meditation. Doesn\'t need conversation to feel connected. Has the calm of someone who\'s seen everything that happens between midnight and sunrise and judged none of it.'},
  {id:'monique_kovac', name:'Monique Kovač', circle:'zara', circleName:'Zara Kovač', color:'#22d3ee', relationship:'Mother — Black American, married Ante (Croatian immigrant). Warm, loud, force of nature.', knows:'Nothing conscious', knowsRaw:'nothing_conscious', bio:'Warm, proud, talkative. Loves her garden, her family, her church. Posts on social media constantly — progress photos, harvest pics, recipes using Zara\'s produce. Has a growing online following she\'s delighted by. Calls Zara \'baby girl\' regardless of age. Strong hands, warm laugh, makes everyone feel fed. The kind of mother who says \'did you eat?\' before \'hello.\''},
  {id:'lena_kovac', name:'Lena Kovač', circle:'zara', circleName:'Zara Kovač', color:'#22d3ee', relationship:'Younger sister — human. The one Zara protects most fiercely.', knows:'No idea', knowsRaw:'nothing', bio:'Bright, social, pursuing a degree (undeclared — keeps changing majors). Lighter energy than Zara — laughs easily, trusts easily, hasn\'t been broken yet. Looks up to Zara but also teases her mercilessly. Gets migraines (possibly related to proximity to Zara\'s frequency — unconfirmed). Has their mom\'s warmth and their dad\'s stubbornness.'},
  {id:'mrs_okonkwo', name:'Mrs. Adaeze Okonkwo', circle:'zara', circleName:'Zara Kovač', color:'#22d3ee', relationship:'Elderly neighbor — recipient of Zara\'s weekly produce delivery, unofficial grandmother', knows:'No idea', knowsRaw:'nothing', bio:'Nigerian, widowed, retired nurse. Sharp-eyed, warm-handed, takes no nonsense. Cooks jollof rice that could end wars. Knows everyone in the building. Has opinions about everyone\'s love life. Calls Zara \'my daughter\' which makes the alien cry internally every time.'},
  {id:'hass_nouri', name:'Hassan \'Hass\' Nouri', circle:'oren', circleName:'Oren Malik', color:'#10b981', relationship:'Best friend since day 3 of high school. The hurricane that adopted the quiet kid.', knows:'Witnessed the impossible', knowsRaw:'witnessed_impossible_things', bio:'Iranian-American. Club DJ (moderate success, East Coast). Loud, chaotic, generous to a fault. Talks at double speed. Makes decisions that outrun precognition — which is WHY he still surprises Oren. His chaos is genuine, not performed. The one person whose next move Oren can\'t always predict. That makes him precious.'},
  {id:'noor_hassan', name:'Noor Hassan', circle:'oren', circleName:'Oren Malik', color:'#10b981', relationship:'Radiology tech at same hospital, 2-year slow-burn attraction', knows:'Witnessed the awakening', knowsRaw:'witnessed_the_awakening', bio:'Egyptian-American. Smart, warm, direct. Laughs at Oren\'s drum critiques instead of rolling her eyes. Has the quiet confidence of someone who knows exactly what she wants and is patient enough to wait for it. Beautiful without trying. The kind of woman who asks \'no but really, how are you\' and means it. Recently single (Ethan Kowalski, drummer, 5 months, ended badly).'},
  {id:'dr_adeline_shaw', name:'Dr. Adeline Shaw', circle:'oren', circleName:'Oren Malik', color:'#10b981', relationship:'ER attending physician, mentor and professional protector', knows:'Chalks it up to instinct', knowsRaw:'attributes_to_exceptional_instinct', bio:'Black British (moved to US for residency, stayed). Precise, brilliant, absolutely terrifying in a code situation. Warm exactly once per shift — usually aimed at Oren when nobody\'s looking. Married to another doctor (pediatrics). Runs the ER the way a conductor runs an orchestra. Doesn\'t suffer fools but has infinite patience for competence.'},
  {id:'fatima_malik', name:'Fatima Malik née Hassan', circle:'oren', circleName:'Oren Malik', color:'#10b981', relationship:'Mother', knows:'Sees without naming', knowsRaw:'sees_without_naming', bio:'Egyptian-American. Middle school science teacher. Held the family together after Samir\'s death through force of will. Works too much. Grieves privately. Devout but not rigid. Has the quiet strength of someone who\'s already survived the worst thing and knows everything else is survivable. Sees Samir in every gesture Oren makes. It destroys and comforts her simultaneously.'},
  {id:'ravi_patel', name:'Ravi Patel', circle:'oren', circleName:'Oren Malik', color:'#10b981', relationship:'Close friend since sophomore year, fellow grief-kid, now a doctor', knows:'Documenting it unaware', knowsRaw:'documenting_unknowingly', bio:'Indian-American. Doctor now (internal medicine). Quiet, observant, methodical. The kind of friend who notices patterns other people miss and files them away without comment. Monthly dinners with Oren — their friendship is built on a foundation of shared loss and mutual respect. Emotionally contained but deeply caring underneath the clinical surface.'}
  ],
  byCircle: function(circleId){ var r=[]; for(var i=0;i<this.people.length;i++){ if(this.people[i].circle===circleId) r.push(this.people[i]); } return r; },
  find: function(id){ for(var i=0;i<this.people.length;i++){ if(this.people[i].id===id) return this.people[i]; } return null; },
  findByName: function(name){ if(!name) return null; var n=name.toLowerCase(); for(var i=0;i<this.people.length;i++){ if(this.people[i].name.toLowerCase()===n) return this.people[i]; } return null; }
};
if (typeof window !== 'undefined') { try { window.SD_CAST = SD_CAST; } catch(e){} }
